// Sitemap generated by the Express app (server/routes/seoRoutes.js) via the adapter.
import { runExpress } from '@/lib/expressAdapter';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(request) {
  const { pathname, search } = new URL(request.url);
  const inner = new Request(`http://localhost${pathname}${search}`, request);
  return runExpress(inner);
}
