/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    const apiTarget = process.env.API_PROXY_TARGET || 'http://localhost:3000';
    return [
      {
        // Proxy all API calls to the Express backend (port 3000)
        source: '/api/:path*',
        destination: `${apiTarget}/api/:path*`
      },
      // SEO routes are generated by the Express API (server/routes/seoRoutes.js)
      // but should resolve on the storefront's own domain, not the API port.
      { source: '/sitemap.xml', destination: `${apiTarget}/sitemap.xml` },
      { source: '/robots.txt', destination: `${apiTarget}/robots.txt` }
    ];
  }
};

export default nextConfig;

